FROM ubuntu

SHELL ["/bin/bash", "-c"]

RUN apt-get update
RUN apt-get install sudo -y
RUN apt-get install -y python3 python3-pip mysql-client
RUN pip3 install mysql-connector-python --break-system-packages

EXPOSE 5000

CMD tail -f /dev/null
