version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: dockerfile_db
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Task_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: dockerfile_app
    container_name: inductions_server_container
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: Task_db

  web:
    build:
      context: .
      dockerfile: dockerfile_web
    container_name: web_app_container
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: Task_db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:8080
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: pass
      
volumes:
  db_data:
