FROM ubuntu

SHELL ["/bin/bash", "-c"]

COPY web /web

RUN apt-get update
RUN apt-get install sudo -y
RUN apt-get install -y python3 python3-pip mysql-client
RUN pip3 install mysql-connector-python --break-system-packages flask gunicorn

EXPOSE 5000

CMD gunicorn -w 4 -b 0.0.0.0:5000 web.app:app

