version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: dockerfile_db
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Task_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: dockerfile_app
    container_name: inductions_server_container
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: Task_db
